networks:
    actIntegradora-net:
       driver: bridge 

services:
    mysql:
        image: mysql:5.7
        container_name: mysqll
        tty: true
        ports:
            - "4208:3306"
        volumes:
            - "./var/libclea/mysql/:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: wordpress
            MYSQL_USER: miusuario
            MYSQL_PASSWORD: mipassword
        networks:
            - actIntegradora-net
 
  

    server:
        image: wordpress:latest
        container_name: wordpress
        ports:
            - "4282:80"
        volumes:
            - "./var/www/html/:/var/www/html"
        environment:
            WORDPRESS_DB_USER: yaacob
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: wordpress
            WORDPRESS_DB_HOST: mysqll
        depends_on:
            - mysql
        networks:
            - actIntegradora-net


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_integradora
        ports:
             - "4283:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: 1234
        depends_on:
              - mysql
        networks:
            - actIntegradora-net
